"use strict";
const assert = require("node:assert/strict");
const {simulate,validate} = require("../real_portfolio_simulator_core.js");
const data={cash_eur:100,positions:[{symbol:"AAA",kind:"stock",value_eur:1000},{symbol:"BTC",kind:"crypto",value_eur:500}]};
assert.equal(validate(data),true);
let r=simulate(data,[],[],20,{stock:-10,crypto:-30});
assert.equal(r.base_eur,1600);
assert.equal(r.current_eur,1600);
assert.equal(r.baseline_stress_eur,1350);
r=simulate(data,[{symbol:"AAA",kind:"stock",amount_eur:200}],[{symbol:"BBB",kind:"stock",amount_eur:250}],20,{stock:-10,crypto:-30});
assert.equal(r.costs_eur,0.90);
assert.equal(r.cash_eur,49.10);
assert.equal(r.current_eur,1599.10);
assert.equal(r.proposed_stress_eur,1344.10);
assert.throws(()=>simulate(data,[{symbol:"AAA",kind:"stock",amount_eur:1001}],[],20),/übersteigt/);
assert.throws(()=>simulate(data,[],[{symbol:"ZZZ",kind:"stock",amount_eur:101}],20),/reicht/);
assert.throws(()=>simulate(data,[],[],20,{stock:-101}),/Stresswert/);
assert.throws(()=>validate({...data,positions:[data.positions[0],data.positions[0]]}),/Doppelte/);
console.log("real_portfolio_simulator: 8 checks PASS");
